# env:
#   WINIT_HIDPI_FACTOR: "1"

env:
  WINIT_X11_SCALE_FACTOR: "1"
  TERM: xterm-256color

scrolling:
  history: 0 # Disable scrolling, we have tmux for it

# TokyoNight Moon
# https://github.com/folke/tokyonight.nvim/blob/main/extras/alacritty/tokyonight_moon.yml
colors:
  # Default colors
  primary:
    background: '0x222436'
    foreground: '0xc8d3f5'

  # Normal colors
  normal:
    black:   '0x1b1d2b'
    red:     '0xff757f'
    green:   '0xc3e88d'
    yellow:  '0xffc777'
    blue:    '0x82aaff'
    magenta: '0xc099ff'
    cyan:    '0x86e1fc'
    white:   '0x828bb8'

  # Bright colors
  bright:
    black:   '0x444a73'
    red:     '0xff757f'
    green:   '0xc3e88d'
    yellow:  '0xffc777'
    blue:    '0x82aaff'
    magenta: '0xc099ff'
    cyan:    '0x86e1fc'
    white:   '0xc8d3f5'

  indexed_colors:
    - { index: 16, color: '0xff966c' }
    - { index: 17, color: '0xc53b53' }

font:
  size: 13 # FONT_SIZE_HERE_FOR_AUTOMATIC_EDITING
  normal:
    style: Regular
    family: mononoki Nerd Font Mono
  bold:
    style: Bold
    family: mononoki Nerd Font Mono
  italic:
    family: mononoki Nerd Font Mono
    style: Italic

draw_bold_text_with_bright_colors: true

mouse:
  hide_when_typing: true

selection:
  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

window:
  opacity: 0.95


