#!/usr/bin/env zsh

# Remember last working directory
cd() {
  builtin cd "$@";
  tmux refresh-client -S
  echo "${PWD}" > ~/.cache/cwd
}

export cd

alias cwd='cd $( cat ~/.cache/cwd )'

# Create directory and cd into it
D() { mkdir -p $1 && cd $1 }

# Go to workspace
alias W='cd ~/workspace'

# Open file with default application
alias O='xdg-open'

# Start editing dotfiles
alias dot='cd ~/.dotfiles && vim'

# time and date
alias today='date +%Y-%m-%d --utc | tr -d \\n'
alias now='date +%Y-%m-%dT%H-%M-%S --utc | tr -d \\n'
alias isodate='date -u +"%Y-%m-%dT%H:%M:%S.%6NZ"'
alias rfc3339=isodate

alias add_timestamp='while read line; do echo "$(date +%Y-%m-%dT%H:%M:%S.$( date +%N | sed 's/......$//' ) --utc) $line"; done'

alias pi='echo 3.14159265359'

alias leave='sleep 10 && exit'

alias ip='ip -c'

# Dir name is current UTC time, without special characters as : to be
# compatible with PATH env var (so you can add this tmp directory to PATH)
# If first argument is defined, it is used as a suffix
# Note: this must be a function: it changes dir in the current shell
DD() {
  date="$( date +%Y/%Y-%m/%Y-%m-%d/%Y%m%dT%H%M%S --utc | tr -d \\n )"
  p="${HOME}/tmp/${date}"
  if [ -n "${1}" ]; then
    p="${p}-${1}"
  fi
  mkdir -p "${p}"
  cd "${p}"
  echo "${p}" > ~/tmp/.last
}

# Change directory to last created directory in tmp
alias last_tmp='cd $( cat ~/tmp/.last )'

alias CLIP='xclip -i -selection clipboard'

# Shortcut for my favorite editor
alias v="${EDITOR}"
alias sv="sudo ${EDITOR}"

# Filesystem usage, human readable
alias df='df -h'
alias du='du -sh'

# Brutally kill
alias ka9='killall -9'
alias k9='kill -9'

# sudo last command
alias fuck='sudo $(fc -ln -1)'

# Highlight
highlight() { grep --color -E "$1|\$"; }

# Grep without buffer
alias nbgrep='stdbuf -o0 -oL grep'

# Disable buffering
alias nb='stdbuf -i0 -o0 -e0'

# I don't use dc, and sometime i mispell cd
alias dc='cd'

# Disable screensaver and screen energy saving (e.g.: during a speech)
alias noscreensaver='xset -dpms s off'

# I often need a python shell for quick math and stuff
alias py="python"

# Show history with yyyy-mm-dd date
alias history="fc -il -t'%F %T' 1"

# the most used (pun not intended) netstat configuration
alias putane="netstat -putane"

#
alias klear="clear ; tmux clear-history ; clear"
