# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "ehci_pci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "rpool/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "rpool/home";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/705E-B3DF";
      fsType = "vfat";
    };

  fileSystems."/home/alepez/.rustup" =
    { device = "rpool/sdk/rust/rustup";
      fsType = "zfs";
    };

  fileSystems."/home/alepez/.cargo" =
    { device = "rpool/sdk/rust/cargo";
      fsType = "zfs";
    };

  swapDevices = [ ];

  virtualisation.virtualbox.guest.enable = true;
}
