# Use case-sensitive completion.
CASE_SENSITIVE="true"

# Disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Disable command auto-correction.
DISABLE_CORRECTION="true"

# Display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Disable marking untracked files under VCS as dirty. This makes repository
# status check for large repositories much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

if [ "${ZSH_NO_TMUX}" != "true" ]; then
  ZSH_TMUX_AUTOSTART=true
  ZSH_TMUX_AUTOCONNECT=false
fi

# History
HISTFILE=~/.history
HISTSIZE=10000
SAVEHIST=10000
HIST_STAMPS="yyyy-mm-dd"

# append to history
setopt appendhistory

# ignore duplicates
setopt hist_ignore_all_dups

# cd to directory without writing cd
setopt autocd

# put a # in front of line and it is ignored. Useful when you want to write
# a command, but execute it later
setopt interactivecomments

# background jobs will be left alone
setopt no_hup

# disable beep
unsetopt beep

# disable extended glob
unsetopt extendedglob

bindkey "^[[5~" history-beginning-search-backward
bindkey "^[[6~" history-beginning-search-forward

# Enable true color for neovim
export NVIM_TUI_ENABLE_TRUE_COLOR=1

stty stop undef
stty start undef

# Source local configurations
if [ -e ~/.zshrc.local ]; then source ~/.zshrc.local; fi

# startship
eval "$(starship init zsh)"
